-- =======================================================================================================================
-- Query 1 :  List all customers with the total number of orders they have placed.
-- SQL Concepts used: JOIN,COUNT() and GROUP BY.
-- =======================================================================================================================

SELECT c.CustomerID, Count(o.OrderID) AS TotalOrders
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID;

-- =======================================================================================================================
-- Query 2: Display all orders with OrderID, OrderDate, Customer full name, Employee full name, and OrderStatus.
-- SQL Concept used:  JOIN
-- =======================================================================================================================

SELECT c.FirstName, c.LastName, o.OrderID, o.OrderDate, o.OrderStatus,e.FirstName, e.LastName
FROM Customers c 
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN Employees e on o.EmployeeID = e.EmployeeID;

-- =======================================================================================================================
-- Query 3: Show all ACTIVE products with their quantity and unit price. 
-- SQL Concept used: WHERE clause.
-- =======================================================================================================================

SELECT ProductName, Quantity, UnitPrice
FROM Products
WHERE Status = 'Active';

-- =======================================================================================================================
-- Query 4: List all orders that are not yet completed.
-- SQL Concept used: WHERE clause.
-- =======================================================================================================================

SELECT *
FROM Orders
WHERE OrderStatus = 'Pending';

-- =======================================================================================================================
-- Query 5: Calculate the total amount paid per order. 
-- SQL Concept used: GROUP BY.
-- =======================================================================================================================

SELECT OrderID, SUM(Amount) AS TotalAmount
FROM Payments
GROUP BY OrderID;

-- =======================================================================================================================
-- Query 6: Find the total revenue generated by the store (completed orders only).
-- SQL Concept used: Hint: JOIN, WHERE clause.
-- =======================================================================================================================

SELECT  SUM (oi.Quantity * oi.UnitPrice) AS TotalRevenue
FROM Orders o
JOIN OrderItems oi on o.OrderID = oi.OrderID
WHERE o.OrderStatus = 'Completed';

-- =======================================================================================================================
-- Query 7: Show the top 5 customers by total spending. 
-- SQL Concept used: GROUP BY , ORDER BY.
-- =======================================================================================================================

SELECT TOP 5 o.CustomerID,
       SUM(oi.Quantity * oi.UnitPrice) AS TotalSpending
FROM Orders o
JOIN OrderItems oi ON o.OrderID = oi.OrderID
GROUP BY o.CustomerID
ORDER BY TotalSpending DESC;

-- =======================================================================================================================
-- Query 8: Calculate the average order value. Hint: First calculate order totals. 
-- SQL Concept used: AVG().
-- =======================================================================================================================

WITH OrdersTotal AS (SELECT OrderID , SUM(Quantity * UnitPrice) AS TotalOrders
FROM OrderItems
GROUP BY OrderID
)
 SELECT  AVG(TotalOrders) AS AverageOrderValue
 FROM OrdersTotal;

-- =======================================================================================================================
-- Query 9: Show total sales revenue per product category. 
-- SQL Concept used: JOIN, GROUP BY.
-- =======================================================================================================================

SELECT p.Category, SUM(oi.Quantity * oi.UnitPrice) AS SalesRevenue
FROM Products p
JOIN OrderItems oi on p.ProductID = oi.ProductID
GROUP BY p.Category;

-- =======================================================================================================================
-- Query 10: Find the number of orders handled by each employee. 
-- SQL Concept used: LEFT JOIN.
-- =======================================================================================================================

SELECT e.FirstName, e.LastName, COUNT(o.OrderID) AS TotalOrders
FROM Employees e
LEFT JOIN Orders o ON e.EmployeeID = o.EmployeeID
GROUP BY e.FirstName, e.LastName;

-- =======================================================================================================================
-- Query 11: Identify customers who have placed more than one order.
-- SQL Concept used: GROUP BY,HAVING ,COUNT().
-- =======================================================================================================================

SELECT CustomerID
FROM Orders 
GROUP BY CustomerID
HAVING COUNT(*) > 1;

-- =======================================================================================================================
-- Query 12: Find products that have never been ordered. 
-- SQL Concept used: LEFT JOIN + IS NULL or NOT EXISTS.
-- =======================================================================================================================

SELECT p.ProductName
FROM Products p
WHERE NOT EXISTS (
    SELECT 1
    FROM OrderItems oi
    WHERE oi.ProductID = p.ProductID);

-- =======================================================================================================================
-- Query 13: Show each order with order total, total paid, and remaining balance. 
-- SQL Concept used: CTEs.
-- =======================================================================================================================

WITH Total_Orders AS (
    SELECT OrderID, SUM(Quantity * UnitPrice) AS OrderTotal
    FROM OrderItems
    GROUP BY OrderID
),
Total_Paid AS (
    SELECT OrderID, SUM(Amount) AS TotalPaid
    FROM Payments
    GROUP BY OrderID
)
SELECT o.OrderID,
       tod.OrderTotal,
       tp.TotalPaid,
       tod.OrderTotal - tp.TotalPaid AS RemainingBalance
FROM Orders o
JOIN Total_Orders tod ON o.OrderID = tod.OrderID
JOIN Total_Paid tp ON o.OrderID = tp.OrderID;

-- =======================================================================================================================
-- Query 14: Identify orders that are partially paid. 
-- SQL Concept used: CTEs.
-- =======================================================================================================================

WITH Total_Orders AS (SELECT OrderID, SUM(Quantity * UnitPrice) AS OrderTotal
FROM OrderItems
GROUP BY OrderID
),
Total_Paid AS (SELECT  o.OrderID, SUM(p.Amount) AS TotalPaid
FROM Orders o
JOIN Payments p ON o.OrderID = p.OrderID
GROUP BY o.OrderID
)
SELECT o.OrderID, tod.OrderTotal, tp.TotalPaid
FROM Orders o 
JOIN Total_Orders tod ON o.OrderID = tod.OrderID
JOIN Total_Paid tp ON o.OrderID = tp.OrderID
GROUP BY o.OrderID, tod.OrderTotal,tp.TotalPaid
HAVING tp.TotalPaid < tod.OrderTotal;

-- =======================================================================================================================
-- Query 15: List employees ranked by total revenue generated.
-- SQL Concepts used: SUM() + RANK().
-- =======================================================================================================================

SELECT e.EmployeeID, e.FirstName,e.LastName,
       SUM(oi.Quantity * oi.UnitPrice) AS TotalRevenueGenerated,
       RANK() OVER (
       ORDER BY SUM(oi.Quantity * oi.UnitPrice) DESC) AS Employee_TotalRevenueGenarated_Rank
FROM Employees e
JOIN Orders o ON e.EmployeeID = o.EmployeeID
JOIN OrderItems oi on o.OrderID = oi.OrderID
GROUP BY e.EmployeeID,e.FirstName,e.LastName;

-- =======================================================================================================================
-- Query 16:  Show monthly sales revenue (year and month).
-- SQL Concepts used: YEAR(), MONTH(), GROUP BY.
-- =======================================================================================================================

SELECT YEAR(o.OrderDate) AS SaleYear, MONTH(o.OrderDate) AS SaleMonth, SUM(oi.Quantity * oi.UnitPrice) AS SalesRevenue
FROM Orders o
JOIN OrderItems oi ON o.OrderID = oi.OrderID
WHERE o.OrderStatus = 'COMPLETED'
GROUP BY  YEAR(o.OrderDate), MONTH(o.OrderDate);

-- =======================================================================================================================
-- Query 17:  Rank customers by total spending using a window function.
-- SQL Concepts used: RANK() OVER().
-- =======================================================================================================================

SELECT o.CustomerID, 
       SUM(io.Quantity * io.UnitPrice) AS TotalSpending,
       RANK() OVER (
       ORDER BY SUM(io.Quantity * io.UnitPrice) DESC) AS CustomerSpending_Rank
FROM Orders o
JOIN OrderItems io ON o.OrderID = io.OrderID
GROUP BY o.CustomerID;

-- =======================================================================================================================
-- Query 18:  For each product, show total quantity sold and total revenue.  
-- SQL Concept used: SUM().
-- =======================================================================================================================

SELECT ProductID,
       SUM(Quantity) AS TotalQuantitySold,
       SUM(Quantity * UnitPrice) AS TotalRevenue
FROM OrderItems
GROUP BY ProductID;

-- Query 19:  Find the most frequently purchased product.
-- SQL Concepts used: ORDER BY,SUM().
SELECT TOP 1 SUM (oi.Quantity) AS SumQuantity, p.ProductName
FROM Products p
JOIN OrderItems oi ON p.ProductID = oi.ProductID
GROUP BY p.ProductName
ORDER BY  SumQuantity DESC;

-- =======================================================================================================================
-- Query 20:   Identify customers whose latest order is still pending. 
-- SQL Concepts used: ROW_NUMBER().
-- =======================================================================================================================

WITH LatestOrders AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY CustomerID
               ORDER BY OrderDate DESC
           ) AS rn
    FROM Orders
)
SELECT c.FirstName, c.LastName, lo.OrderDate
FROM LatestOrders lo
JOIN Customers c ON lo.CustomerID = c.CustomerID
WHERE lo.rn = 1
AND lo.OrderStatus = 'PENDING';





